//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.5.2+3431f76
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Column Settings</summary>
	[PublishedModel("columnSettings")]
	public partial class ColumnSettings : PublishedElementModel, ICustomProperties
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.2+3431f76")]
		public new const string ModelTypeAlias = "columnSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.2+3431f76")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.2+3431f76")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.2+3431f76")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<ColumnSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public ColumnSettings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Attributes: *Optional: Will be placed within the [section] tag.  User is responsible for properly closing attributes.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.2+3431f76")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("attributes")]
		public virtual string Attributes => this.Value<string>(_publishedValueFallback, "attributes");

		///<summary>
		/// Row Spacing
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.2+3431f76")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("rowSpacing")]
		public virtual global::System.Collections.Generic.IEnumerable<string> RowSpacing => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "rowSpacing");

		///<summary>
		/// Vertically Align Content: *default is "None".
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.2+3431f76")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("verticallyAlignContent")]
		public virtual string VerticallyAlignContent => this.Value<string>(_publishedValueFallback, "verticallyAlignContent");

		///<summary>
		/// Container Attributes: *Optional attributes added to pre-defined tags  ex:  data-value="X"
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.2+3431f76")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("containerAttributes")]
		public virtual string ContainerAttributes => global::Umbraco.Cms.Web.Common.PublishedModels.CustomProperties.GetContainerAttributes(this, _publishedValueFallback);

		///<summary>
		/// Container Classes: *Optional classes added to pre-defined tags  ex:  interior-wrap  align-center-middle
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.2+3431f76")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("containerClasses")]
		public virtual string ContainerClasses => global::Umbraco.Cms.Web.Common.PublishedModels.CustomProperties.GetContainerClasses(this, _publishedValueFallback);

		///<summary>
		/// Custom Scripts: *Optional styles and scripts can be added within the outer-most tag.    [example] &lt;style scoped&gt; h1 {font-size:50px; } &lt;/ style&gt;
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.2+3431f76")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("customScripts")]
		public virtual string CustomScripts => global::Umbraco.Cms.Web.Common.PublishedModels.CustomProperties.GetCustomScripts(this, _publishedValueFallback);

		///<summary>
		/// Outer-Most Attributes: *Optional attributes added to the outer-most tag.  ex:  data-value="X"
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.2+3431f76")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("outerMostAttributes")]
		public virtual string OuterMostAttributes => global::Umbraco.Cms.Web.Common.PublishedModels.CustomProperties.GetOuterMostAttributes(this, _publishedValueFallback);

		///<summary>
		/// Outer-Most Class: *Optional classes added to the outer-most tag.   ex:  dark-text light-text  no-angle left-angle left-angle-soft right-angle right-angle-soft
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.2+3431f76")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("outerMostClass")]
		public virtual string OuterMostClass => global::Umbraco.Cms.Web.Common.PublishedModels.CustomProperties.GetOuterMostClass(this, _publishedValueFallback);
	}
}
