//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bl.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Battery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Battery()
        {
            this.PowerSources = new HashSet<PowerSource>();
        }
    
        public int BatteriesId { get; set; }
        public Nullable<int> BatteryTypeId { get; set; }
        public Nullable<int> BatteryQuantity { get; set; }
        public bool HasBatteries { get; set; }
    
        public virtual BatteryType BatteryType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PowerSource> PowerSources { get; set; }
    }
}
