//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bl.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EFPrepperSuiteDb : DbContext
    {
        public EFPrepperSuiteDb()
            : base("name=EFPrepperSuiteDb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Battery> Batteries { get; set; }
        public virtual DbSet<BatteryType> BatteryTypes { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<FoodType> FoodTypes { get; set; }
        public virtual DbSet<Fuel> Fuels { get; set; }
        public virtual DbSet<FuelType> FuelTypes { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<MeasurementState> MeasurementStates { get; set; }
        public virtual DbSet<MeasurementSystem> MeasurementSystems { get; set; }
        public virtual DbSet<MeasurementType> MeasurementTypes { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberTool> MemberTools { get; set; }
        public virtual DbSet<PowerSource> PowerSources { get; set; }
        public virtual DbSet<ScrumChecklist> ScrumChecklists { get; set; }
        public virtual DbSet<ScrumStatusList> ScrumStatusLists { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<Tool> Tools { get; set; }
        public virtual DbSet<Volume> Volumes { get; set; }
        public virtual DbSet<ScrumCard> ScrumCards { get; set; }
        public virtual DbSet<ScrumActivity> ScrumActivities { get; set; }
    }
}
