//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bl.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemId { get; set; }
        public string Name { get; set; }
        public int AccountId { get; set; }
        public int ToolId { get; set; }
        public Nullable<int> MemberId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> FoodTypeId { get; set; }
        public Nullable<int> PowerSourceId { get; set; }
        public Nullable<int> VolumeId { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public System.DateTime CreatedTimestamp { get; set; }
        public System.DateTime LastUpdatedTimestamp { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Category Category { get; set; }
        public virtual FoodType FoodType { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Location Location { get; set; }
        public virtual Member Member { get; set; }
        public virtual PowerSource PowerSource { get; set; }
        public virtual Tool Tool { get; set; }
        public virtual Season Season { get; set; }
        public virtual Volume Volume { get; set; }
    }
}
