//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bl.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasurementType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MeasurementType()
        {
            this.Volumes = new HashSet<Volume>();
        }
    
        public int MeasurementTypeId { get; set; }
        public string Type { get; set; }
        public string Abbr { get; set; }
        public decimal BaseMetricValue { get; set; }
        public string BaseMetricType { get; set; }
        public string BaseMetricAbbr { get; set; }
        public int MeasurementSystemId { get; set; }
        public int MeasurementStateId { get; set; }
    
        public virtual MeasurementState MeasurementState { get; set; }
        public virtual MeasurementSystem MeasurementSystem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Volume> Volumes { get; set; }
    }
}
