//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bl.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberTool
    {
        public int MemberToolId { get; set; }
        public int AccountId { get; set; }
        public int ToolId { get; set; }
        public int ColorId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Color Color { get; set; }
        public virtual Tool Tool { get; set; }
    }
}
