//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bl.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Volume
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Volume()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int VolumeId { get; set; }
        public Nullable<int> MeasurementTypeId { get; set; }
        public Nullable<decimal> Units { get; set; }
        public int MeasurementSystemId { get; set; }
        public Nullable<int> MeasurementStateId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item> Items { get; set; }
        public virtual MeasurementState MeasurementState { get; set; }
        public virtual MeasurementSystem MeasurementSystem { get; set; }
        public virtual MeasurementType MeasurementType { get; set; }
    }
}
