//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.5.1+2e068bb
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace www.Models.PublishedModels
{
	/// <summary>Column Settings</summary>
	[PublishedModel("columnSettings")]
	public partial class ColumnSettings : PublishedElementModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		public new const string ModelTypeAlias = "columnSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<ColumnSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public ColumnSettings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Background Color: *Note: Always add color as #aabbcc
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("backgroundColor")]
		public virtual string BackgroundColor => this.Value<string>(_publishedValueFallback, "backgroundColor");

		///<summary>
		/// Background Image: *Optional: Image will be centered and stretch to fill space.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("backgroundImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops BackgroundImage => this.Value<global::Umbraco.Cms.Core.Models.MediaWithCrops>(_publishedValueFallback, "backgroundImage");

		///<summary>
		/// Cell Classes: *Optional classes added along with cell
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cellClasses")]
		public virtual string CellClasses => this.Value<string>(_publishedValueFallback, "cellClasses");

		///<summary>
		/// Container Classes: *Optional classes added along with grid-container
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("gridContainerClasses")]
		public virtual string GridContainerClasses => this.Value<string>(_publishedValueFallback, "gridContainerClasses");

		///<summary>
		/// Row Classes: *Optional classes added along with grid-x
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("gridXClasses")]
		public virtual string GridXclasses => this.Value<string>(_publishedValueFallback, "gridXClasses");

		///<summary>
		/// Optional Cell Classes: *These are pre-built classes that can be added to the outer cell.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("optionalCellClasses")]
		public virtual global::System.Collections.Generic.IEnumerable<string> OptionalCellClasses => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "optionalCellClasses");

		///<summary>
		/// Optional Container Classes: *These are pre-built classes that can be added to the inner container.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("optionalContainerClasses")]
		public virtual global::System.Collections.Generic.IEnumerable<string> OptionalContainerClasses => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "optionalContainerClasses");

		///<summary>
		/// Optional Row Classes: *These are pre-built classes that can be added to the row.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("optionalRowClasses")]
		public virtual global::System.Collections.Generic.IEnumerable<string> OptionalRowClasses => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "optionalRowClasses");

		///<summary>
		/// Optional Section Classes: *These are pre-built classes that can be added to the outer-most section.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("optionalSectionClasses")]
		public virtual global::System.Collections.Generic.IEnumerable<string> OptionalSectionClasses => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "optionalSectionClasses");

		///<summary>
		/// Row Anchor Name: *Optional: Will add an anchor point that can be called by adding #[name] at the end of the URL.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("pgid")]
		public virtual string Pgid => this.Value<string>(_publishedValueFallback, "pgid");

		///<summary>
		/// Row Margin: *The default is none
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("rowMargin")]
		public virtual string RowMargin => this.Value<string>(_publishedValueFallback, "rowMargin");

		///<summary>
		/// Row Padding: *The default is none
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("rowPadding")]
		public virtual string RowPadding => this.Value<string>(_publishedValueFallback, "rowPadding");

		///<summary>
		/// Section Class: *Optional classes added to the section.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sectionClasses")]
		public virtual string SectionClasses => this.Value<string>(_publishedValueFallback, "sectionClasses");

		///<summary>
		/// White Text: *Optional: Overrides text colors to be white.  Used along with background image.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[ImplementPropertyType("whiteText")]
		public virtual bool WhiteText => this.Value<bool>(_publishedValueFallback, "whiteText");
	}
}
