//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.5.1+2e068bb
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace www.Models.PublishedModels
{
	/// <summary>NC Recipe Ingredient</summary>
	[PublishedModel("ncRecipeIngredient")]
	public partial class NcRecipeIngredient : PublishedElementModel
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		public new const string ModelTypeAlias = "ncRecipeIngredient";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<NcRecipeIngredient, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public NcRecipeIngredient(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Absolute Qty: Numeric version of Qty (ex: .5)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[ImplementPropertyType("AbsoluteQty")]
		public virtual decimal AbsoluteQty => this.Value<decimal>(_publishedValueFallback, "AbsoluteQty");

		///<summary>
		/// Display Quantity: Quantity as it should be displayed (ex: 1/2)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("DisplayQuantity")]
		public virtual string DisplayQuantity => this.Value<string>(_publishedValueFallback, "DisplayQuantity");

		///<summary>
		/// Imported Ingredient Id
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ImportedIngredientId")]
		public virtual string ImportedIngredientId => this.Value<string>(_publishedValueFallback, "ImportedIngredientId");

		///<summary>
		/// Imported Recipe Id
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ImportedRecipeId")]
		public virtual string ImportedRecipeId => this.Value<string>(_publishedValueFallback, "ImportedRecipeId");

		///<summary>
		/// Imported Sequence Number
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ImportedSequenceNumber")]
		public virtual string ImportedSequenceNumber => this.Value<string>(_publishedValueFallback, "ImportedSequenceNumber");

		///<summary>
		/// ImportedStepNumber
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ImportedStepNumber")]
		public virtual string ImportedStepNumber => this.Value<string>(_publishedValueFallback, "ImportedStepNumber");

		///<summary>
		/// Imported UnitName
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ImportedUnitName")]
		public virtual string ImportedUnitName => this.Value<string>(_publishedValueFallback, "ImportedUnitName");

		///<summary>
		/// Ingredient: Ingredient
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("Ingredient")]
		public virtual string Ingredient => this.Value<string>(_publishedValueFallback, "Ingredient");

		///<summary>
		/// Ingredient Preparation: Optional (ex: diced, steamed)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("IngredientPrep")]
		public virtual string IngredientPrep => this.Value<string>(_publishedValueFallback, "IngredientPrep");

		///<summary>
		/// Unit
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("IngredientUnit")]
		public virtual global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent IngredientUnit => this.Value<global::Umbraco.Cms.Core.Models.PublishedContent.IPublishedContent>(_publishedValueFallback, "IngredientUnit");

		///<summary>
		/// Is Optional: Is this an optional ingredient?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[ImplementPropertyType("IsOptional")]
		public virtual bool IsOptional => this.Value<bool>(_publishedValueFallback, "IsOptional");

		///<summary>
		/// Measurement Note: If provided will be displayed after the Ingredient (ex: about 4 large)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("MeasurementNote")]
		public virtual string MeasurementNote => this.Value<string>(_publishedValueFallback, "MeasurementNote");

		///<summary>
		/// Measurement in Ounces: Optional - useful for future possible recipe scaling
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[ImplementPropertyType("MeasurementOz")]
		public virtual decimal MeasurementOz => this.Value<decimal>(_publishedValueFallback, "MeasurementOz");

		///<summary>
		/// Quantity Qualifier: Optional - qualifies the quantity, if needed. (ex: small, large, 6 oz)
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("QuantityQualifier")]
		public virtual string QuantityQualifier => this.Value<string>(_publishedValueFallback, "QuantityQualifier");

		///<summary>
		/// Subhead / Note: For Text which should appear in the Ingredients area, but isn't an ingredient
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("SubheadNote")]
		public virtual string SubheadNote => this.Value<string>(_publishedValueFallback, "SubheadNote");
	}
}
