//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v13.5.1+2e068bb
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace www.Models.PublishedModels
{
	/// <summary>Product</summary>
	[PublishedModel("Product")]
	public partial class Product : PublishedContentModel, ICall2Action, ICompPageSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		public new const string ModelTypeAlias = "Product";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedSnapshotAccessor publishedSnapshotAccessor)
			=> PublishedModelUtility.GetModelContentType(publishedSnapshotAccessor, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedSnapshotAccessor publishedSnapshotAccessor, Expression<Func<Product, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(publishedSnapshotAccessor), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Product(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Added Sugar
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("addedSugar")]
		public virtual string AddedSugar => this.Value<string>(_publishedValueFallback, "addedSugar");

		///<summary>
		/// Added Sugar Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("addedSugarPercent")]
		public virtual string AddedSugarPercent => this.Value<string>(_publishedValueFallback, "addedSugarPercent");

		///<summary>
		/// Added Sugar Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("addedSugarPercentPerMsr")]
		public virtual string AddedSugarPercentPerMsr => this.Value<string>(_publishedValueFallback, "addedSugarPercentPerMsr");

		///<summary>
		/// Added Sugar
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("addedSugarPerMsr")]
		public virtual string AddedSugarPerMsr => this.Value<string>(_publishedValueFallback, "addedSugarPerMsr");

		///<summary>
		/// Additional Images
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("additionalImages")]
		public virtual global::System.Collections.Generic.IEnumerable<string> AdditionalImages => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "additionalImages");

		///<summary>
		/// Allergens
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("allergens")]
		public virtual global::System.Collections.Generic.IEnumerable<string> Allergens => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "allergens");

		///<summary>
		/// Attribute- Brand
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("attributeBrand")]
		public virtual string AttributeBrand => this.Value<string>(_publishedValueFallback, "attributeBrand");

		///<summary>
		/// Attribute- Cooking Status
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("attributeCookingStatus")]
		public virtual string AttributeCookingStatus => this.Value<string>(_publishedValueFallback, "attributeCookingStatus");

		///<summary>
		/// Attribute- Fresh-Frozen
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("attributeFreshFrozen")]
		public virtual string AttributeFreshFrozen => this.Value<string>(_publishedValueFallback, "attributeFreshFrozen");

		///<summary>
		/// Attribute- Preparation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("attributePreparation")]
		public virtual string AttributePreparation => this.Value<string>(_publishedValueFallback, "attributePreparation");

		///<summary>
		/// Attribute- Product Types
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("attributeProductTypes")]
		public virtual global::System.Collections.Generic.IEnumerable<string> AttributeProductTypes => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "attributeProductTypes");

		///<summary>
		/// Attribute- Protein
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("attributeProtein")]
		public virtual string AttributeProtein => this.Value<string>(_publishedValueFallback, "attributeProtein");

		///<summary>
		/// Attributes
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("attributes")]
		public virtual global::System.Collections.Generic.IEnumerable<string> Attributes => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "attributes");

		///<summary>
		/// Average Piece Size
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("averagePieceSize")]
		public virtual string AveragePieceSize => this.Value<string>(_publishedValueFallback, "averagePieceSize");

		///<summary>
		/// Brand Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("BrandName")]
		public virtual string BrandName => this.Value<string>(_publishedValueFallback, "BrandName");

		///<summary>
		/// Calcium
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("calcium")]
		public virtual string Calcium => this.Value<string>(_publishedValueFallback, "calcium");

		///<summary>
		/// Calcium Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("calciumPercent")]
		public virtual string CalciumPercent => this.Value<string>(_publishedValueFallback, "calciumPercent");

		///<summary>
		/// Calcium Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("calciumPercentPerMsr")]
		public virtual string CalciumPercentPerMsr => this.Value<string>(_publishedValueFallback, "calciumPercentPerMsr");

		///<summary>
		/// Calcium
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("calciumPerMsr")]
		public virtual string CalciumPerMsr => this.Value<string>(_publishedValueFallback, "calciumPerMsr");

		///<summary>
		/// Calories
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("calories")]
		public virtual string Calories => this.Value<string>(_publishedValueFallback, "calories");

		///<summary>
		/// Calories from Fat
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("caloriesFromFat")]
		public virtual string CaloriesFromFat => this.Value<string>(_publishedValueFallback, "caloriesFromFat");

		///<summary>
		/// Calories from Fat
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("caloriesFromFatPerMsr")]
		public virtual string CaloriesFromFatPerMsr => this.Value<string>(_publishedValueFallback, "caloriesFromFatPerMsr");

		///<summary>
		/// Calories
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("caloriesPerMsr")]
		public virtual string CaloriesPerMsr => this.Value<string>(_publishedValueFallback, "caloriesPerMsr");

		///<summary>
		/// Case Cube
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("caseCube")]
		public virtual string CaseCube => this.Value<string>(_publishedValueFallback, "caseCube");

		///<summary>
		/// Cases Per Pallet
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("casesPerPallet")]
		public virtual string CasesPerPallet => this.Value<string>(_publishedValueFallback, "casesPerPallet");

		///<summary>
		/// Cholesterol
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cholesterol")]
		public virtual string Cholesterol => this.Value<string>(_publishedValueFallback, "cholesterol");

		///<summary>
		/// Cholesterol Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cholesterolPercent")]
		public virtual string CholesterolPercent => this.Value<string>(_publishedValueFallback, "cholesterolPercent");

		///<summary>
		/// Cholesterol Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cholesterolPercentPerMsr")]
		public virtual string CholesterolPercentPerMsr => this.Value<string>(_publishedValueFallback, "cholesterolPercentPerMsr");

		///<summary>
		/// Cholesterol
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cholesterolPerMsr")]
		public virtual string CholesterolPerMsr => this.Value<string>(_publishedValueFallback, "cholesterolPerMsr");

		///<summary>
		/// Cook Level
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("cookLevel")]
		public virtual string CookLevel => this.Value<string>(_publishedValueFallback, "cookLevel");

		///<summary>
		/// Dietary Fiber
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("dietaryFiber")]
		public virtual string DietaryFiber => this.Value<string>(_publishedValueFallback, "dietaryFiber");

		///<summary>
		/// Dietary Fiber Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("dietaryFiberPercent")]
		public virtual string DietaryFiberPercent => this.Value<string>(_publishedValueFallback, "dietaryFiberPercent");

		///<summary>
		/// Dietary Fiber Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("dietaryFiberPercentPerMsr")]
		public virtual string DietaryFiberPercentPerMsr => this.Value<string>(_publishedValueFallback, "dietaryFiberPercentPerMsr");

		///<summary>
		/// Dietary Fiber
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("dietaryFiberPerMsr")]
		public virtual string DietaryFiberPerMsr => this.Value<string>(_publishedValueFallback, "dietaryFiberPerMsr");

		///<summary>
		/// Dimensions
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("dimensions")]
		public virtual string Dimensions => this.Value<string>(_publishedValueFallback, "dimensions");

		///<summary>
		/// Functional Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("functionalName")]
		public virtual string FunctionalName => this.Value<string>(_publishedValueFallback, "functionalName");

		///<summary>
		/// Gtin
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("gtin")]
		public virtual string Gtin => this.Value<string>(_publishedValueFallback, "gtin");

		///<summary>
		/// Ingredients
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ingredients")]
		public virtual string Ingredients => this.Value<string>(_publishedValueFallback, "ingredients");

		///<summary>
		/// Iron
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("iron")]
		public virtual string Iron => this.Value<string>(_publishedValueFallback, "iron");

		///<summary>
		/// Iron Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ironPercent")]
		public virtual string IronPercent => this.Value<string>(_publishedValueFallback, "ironPercent");

		///<summary>
		/// Iron Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ironPercentPerMsr")]
		public virtual string IronPercentPerMsr => this.Value<string>(_publishedValueFallback, "ironPercentPerMsr");

		///<summary>
		/// Iron
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ironPerMsr")]
		public virtual string IronPerMsr => this.Value<string>(_publishedValueFallback, "ironPerMsr");

		///<summary>
		/// Json Data: *Parsing tool: https://jsonviewer.stack.hu/
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("jsonData")]
		public virtual string JsonData => this.Value<string>(_publishedValueFallback, "jsonData");

		///<summary>
		/// Last Modified: *Last time product was modified in 1WS.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[ImplementPropertyType("lastModified")]
		public virtual global::System.DateTime LastModified => this.Value<global::System.DateTime>(_publishedValueFallback, "lastModified");

		///<summary>
		/// Max Case Weight
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("maxCaseWeight")]
		public virtual string MaxCaseWeight => this.Value<string>(_publishedValueFallback, "maxCaseWeight");

		///<summary>
		/// Pallet Tie Hi
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("palletTieHi")]
		public virtual string PalletTieHi => this.Value<string>(_publishedValueFallback, "palletTieHi");

		///<summary>
		/// Potassium
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("potassium")]
		public virtual string Potassium => this.Value<string>(_publishedValueFallback, "potassium");

		///<summary>
		/// Potassium Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("potassiumPercent")]
		public virtual string PotassiumPercent => this.Value<string>(_publishedValueFallback, "potassiumPercent");

		///<summary>
		/// Potassium Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("potassiumPercentPerMsr")]
		public virtual string PotassiumPercentPerMsr => this.Value<string>(_publishedValueFallback, "potassiumPercentPerMsr");

		///<summary>
		/// Potassium
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("potassiumPerMsr")]
		public virtual string PotassiumPerMsr => this.Value<string>(_publishedValueFallback, "potassiumPerMsr");

		///<summary>
		/// Primary Image Url
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("primaryImageUrl")]
		public virtual string PrimaryImageUrl => this.Value<string>(_publishedValueFallback, "primaryImageUrl");

		///<summary>
		/// Product Code
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("ProductCode")]
		public virtual string ProductCode => this.Value<string>(_publishedValueFallback, "ProductCode");

		///<summary>
		/// Protein
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("protein")]
		public virtual string Protein => this.Value<string>(_publishedValueFallback, "protein");

		///<summary>
		/// Protein Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("proteinPercent")]
		public virtual string ProteinPercent => this.Value<string>(_publishedValueFallback, "proteinPercent");

		///<summary>
		/// Protein Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("proteinPercentPerMsr")]
		public virtual string ProteinPercentPerMsr => this.Value<string>(_publishedValueFallback, "proteinPercentPerMsr");

		///<summary>
		/// Protein
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("proteinPerMsr")]
		public virtual string ProteinPerMsr => this.Value<string>(_publishedValueFallback, "proteinPerMsr");

		///<summary>
		/// Raw- Attributes
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("rawAttributes")]
		public virtual global::System.Collections.Generic.IEnumerable<string> RawAttributes => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "rawAttributes");

		///<summary>
		/// Raw- Brand
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("rawBrand")]
		public virtual string RawBrand => this.Value<string>(_publishedValueFallback, "rawBrand");

		///<summary>
		/// Raw- Cooking Status
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("rawCookingStatus")]
		public virtual string RawCookingStatus => this.Value<string>(_publishedValueFallback, "rawCookingStatus");

		///<summary>
		/// Raw- Fresh Frozen
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("rawFreshFrozen")]
		public virtual string RawFreshFrozen => this.Value<string>(_publishedValueFallback, "rawFreshFrozen");

		///<summary>
		/// Raw- Preparation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("rawPreparation")]
		public virtual string RawPreparation => this.Value<string>(_publishedValueFallback, "rawPreparation");

		///<summary>
		/// Raw- Protein
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("rawProtein")]
		public virtual string RawProtein => this.Value<string>(_publishedValueFallback, "rawProtein");

		///<summary>
		/// Saturated Fat
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("saturatedFat")]
		public virtual string SaturatedFat => this.Value<string>(_publishedValueFallback, "saturatedFat");

		///<summary>
		/// Saturated Fat Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("saturatedFatPercent")]
		public virtual string SaturatedFatPercent => this.Value<string>(_publishedValueFallback, "saturatedFatPercent");

		///<summary>
		/// Saturated Fat Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("saturatedFatPercentPerMsr")]
		public virtual string SaturatedFatPercentPerMsr => this.Value<string>(_publishedValueFallback, "saturatedFatPercentPerMsr");

		///<summary>
		/// Saturated Fat
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("saturatedFatPerMsr")]
		public virtual string SaturatedFatPerMsr => this.Value<string>(_publishedValueFallback, "saturatedFatPerMsr");

		///<summary>
		/// Serving Size
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("servingSize")]
		public virtual string ServingSize => this.Value<string>(_publishedValueFallback, "servingSize");

		///<summary>
		/// Serving Size Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("servingSizeDescription")]
		public virtual string ServingSizeDescription => this.Value<string>(_publishedValueFallback, "servingSizeDescription");

		///<summary>
		/// Serving Size
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("servingSizePerMsr")]
		public virtual string ServingSizePerMsr => this.Value<string>(_publishedValueFallback, "servingSizePerMsr");

		///<summary>
		/// Servings Per Case
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("servingsPerCase")]
		public virtual string ServingsPerCase => this.Value<string>(_publishedValueFallback, "servingsPerCase");

		///<summary>
		/// Shelf Life
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("shelfLife")]
		public virtual string ShelfLife => this.Value<string>(_publishedValueFallback, "shelfLife");

		///<summary>
		/// Sodium
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sodium")]
		public virtual string Sodium => this.Value<string>(_publishedValueFallback, "sodium");

		///<summary>
		/// Sodium Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sodiumPercent")]
		public virtual string SodiumPercent => this.Value<string>(_publishedValueFallback, "sodiumPercent");

		///<summary>
		/// Sodium Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sodiumPercentPerMsr")]
		public virtual string SodiumPercentPerMsr => this.Value<string>(_publishedValueFallback, "sodiumPercentPerMsr");

		///<summary>
		/// Sodium
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sodiumPerMsr")]
		public virtual string SodiumPerMsr => this.Value<string>(_publishedValueFallback, "sodiumPerMsr");

		///<summary>
		/// Storage Method
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storageMethod")]
		public virtual string StorageMethod => this.Value<string>(_publishedValueFallback, "storageMethod");

		///<summary>
		/// Storage Temperature
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("storageTemperature")]
		public virtual string StorageTemperature => this.Value<string>(_publishedValueFallback, "storageTemperature");

		///<summary>
		/// Sugars
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sugars")]
		public virtual string Sugars => this.Value<string>(_publishedValueFallback, "sugars");

		///<summary>
		/// Sugars
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("sugarsPerMsr")]
		public virtual string SugarsPerMsr => this.Value<string>(_publishedValueFallback, "sugarsPerMsr");

		///<summary>
		/// Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("title")]
		public virtual string Title => this.Value<string>(_publishedValueFallback, "title");

		///<summary>
		/// Total Carbohydrates
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("totalCarbohydrates")]
		public virtual string TotalCarbohydrates => this.Value<string>(_publishedValueFallback, "totalCarbohydrates");

		///<summary>
		/// Total Carbohydrates Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("totalCarbohydratesPercent")]
		public virtual string TotalCarbohydratesPercent => this.Value<string>(_publishedValueFallback, "totalCarbohydratesPercent");

		///<summary>
		/// Total Carbohydrates Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("totalCarbohydratesPercentPerMsr")]
		public virtual string TotalCarbohydratesPercentPerMsr => this.Value<string>(_publishedValueFallback, "totalCarbohydratesPercentPerMsr");

		///<summary>
		/// Total Carbohydrates
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("totalCarbohydratesPerMsr")]
		public virtual string TotalCarbohydratesPerMsr => this.Value<string>(_publishedValueFallback, "totalCarbohydratesPerMsr");

		///<summary>
		/// Total Fat
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("totalFat")]
		public virtual string TotalFat => this.Value<string>(_publishedValueFallback, "totalFat");

		///<summary>
		/// Total Fat Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("totalFatPercent")]
		public virtual string TotalFatPercent => this.Value<string>(_publishedValueFallback, "totalFatPercent");

		///<summary>
		/// Total Fat Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("totalFatPercentPerMsr")]
		public virtual string TotalFatPercentPerMsr => this.Value<string>(_publishedValueFallback, "totalFatPercentPerMsr");

		///<summary>
		/// Total Fat
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("totalFatPerMsr")]
		public virtual string TotalFatPerMsr => this.Value<string>(_publishedValueFallback, "totalFatPerMsr");

		///<summary>
		/// Trade Item Keywords
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tradeItemKeywords")]
		public virtual global::System.Collections.Generic.IEnumerable<string> TradeItemKeywords => this.Value<global::System.Collections.Generic.IEnumerable<string>>(_publishedValueFallback, "tradeItemKeywords");

		///<summary>
		/// Trade Item Marketing Message
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("tradeItemMarketingMessage")]
		public virtual string TradeItemMarketingMessage => this.Value<string>(_publishedValueFallback, "tradeItemMarketingMessage");

		///<summary>
		/// Trans Fat
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("transFat")]
		public virtual string TransFat => this.Value<string>(_publishedValueFallback, "transFat");

		///<summary>
		/// Trans Fat
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("transFatPerMsr")]
		public virtual string TransFatPerMsr => this.Value<string>(_publishedValueFallback, "transFatPerMsr");

		///<summary>
		/// Vitamin A Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("vitaminAPercent")]
		public virtual string VitaminApercent => this.Value<string>(_publishedValueFallback, "vitaminAPercent");

		///<summary>
		/// Vitamin A Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("vitaminAPercentPerMsr")]
		public virtual string VitaminApercentPerMsr => this.Value<string>(_publishedValueFallback, "vitaminAPercentPerMsr");

		///<summary>
		/// Vitamin C Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("vitaminCPercent")]
		public virtual string VitaminCpercent => this.Value<string>(_publishedValueFallback, "vitaminCPercent");

		///<summary>
		/// Vitamin C Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("vitaminCPercentPerMsr")]
		public virtual string VitaminCpercentPerMsr => this.Value<string>(_publishedValueFallback, "vitaminCPercentPerMsr");

		///<summary>
		/// Vitamin D
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("vitaminD")]
		public virtual string VitaminD => this.Value<string>(_publishedValueFallback, "vitaminD");

		///<summary>
		/// Vitamin D Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("vitaminDPercent")]
		public virtual string VitaminDpercent => this.Value<string>(_publishedValueFallback, "vitaminDPercent");

		///<summary>
		/// Vitamin D Percent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("vitaminDPercentPerMsr")]
		public virtual string VitaminDpercentPerMsr => this.Value<string>(_publishedValueFallback, "vitaminDPercentPerMsr");

		///<summary>
		/// Vitamin D
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("vitaminDPerMsr")]
		public virtual string VitaminDperMsr => this.Value<string>(_publishedValueFallback, "vitaminDPerMsr");

		///<summary>
		/// Weight
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("weight")]
		public virtual string Weight => this.Value<string>(_publishedValueFallback, "weight");

		///<summary>
		/// Background Image: Set behind the Call 2 Action
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("backgroundImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops BackgroundImage => global::www.Models.PublishedModels.Call2Action.GetBackgroundImage(this, _publishedValueFallback);

		///<summary>
		/// Embed Vimeo Id: *This option will change the Product Image into a button for an embedded video.  For now, only use Vimeo embeds.  Enter the ID ONLY!
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("embedVimeoId")]
		public virtual string EmbedVimeoId => global::www.Models.PublishedModels.Call2Action.GetEmbedVimeoId(this, _publishedValueFallback);

		///<summary>
		/// Embed Vimeo Title: *Only used when a vimeo embed id is provided.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("embedVimeoTitle")]
		public virtual string EmbedVimeoTitle => global::www.Models.PublishedModels.Call2Action.GetEmbedVimeoTitle(this, _publishedValueFallback);

		///<summary>
		/// Lead-In Text: Text above the Call 2 Action section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("leadInText")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString LeadInText => global::www.Models.PublishedModels.Call2Action.GetLeadInText(this, _publishedValueFallback);

		///<summary>
		/// Message
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("message")]
		public virtual global::Umbraco.Cms.Core.Strings.IHtmlEncodedString Message => global::www.Models.PublishedModels.Call2Action.GetMessage(this, _publishedValueFallback);

		///<summary>
		/// Product Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("productImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops ProductImage => global::www.Models.PublishedModels.Call2Action.GetProductImage(this, _publishedValueFallback);

		///<summary>
		/// Show Call-2-Action
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[ImplementPropertyType("showCall2Action")]
		public virtual bool ShowCall2Action => global::www.Models.PublishedModels.Call2Action.GetShowCall2Action(this, _publishedValueFallback);

		///<summary>
		/// Custom Scripts: *Will be inserted into a {script} tag at the end of the {body} tag.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("customScripts")]
		public virtual string CustomScripts => global::www.Models.PublishedModels.CompPageSettings.GetCustomScripts(this, _publishedValueFallback);

		///<summary>
		/// Custom Styles: *Will be inserted into a {style} tag within the {head}
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("customStyles")]
		public virtual string CustomStyles => global::www.Models.PublishedModels.CompPageSettings.GetCustomStyles(this, _publishedValueFallback);

		///<summary>
		/// Meta Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("MetaDescription")]
		public virtual string MetaDescription => global::www.Models.PublishedModels.CompPageSettings.GetMetaDescription(this, _publishedValueFallback);

		///<summary>
		/// Meta Keywords
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("MetaKeywords")]
		public virtual string MetaKeywords => global::www.Models.PublishedModels.CompPageSettings.GetMetaKeywords(this, _publishedValueFallback);

		///<summary>
		/// Meta Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("MetaTitle")]
		public virtual string MetaTitle => global::www.Models.PublishedModels.CompPageSettings.GetMetaTitle(this, _publishedValueFallback);

		///<summary>
		/// Open Graph Description: If blank, will use Meta Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("OpenGraphDescription")]
		public virtual string OpenGraphDescription => global::www.Models.PublishedModels.CompPageSettings.GetOpenGraphDescription(this, _publishedValueFallback);

		///<summary>
		/// Open Graph Preview Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("OpenGraphImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops OpenGraphImage => global::www.Models.PublishedModels.CompPageSettings.GetOpenGraphImage(this, _publishedValueFallback);

		///<summary>
		/// Open Graph Title: If blank, will use Meta Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("OpenGraphTitle")]
		public virtual string OpenGraphTitle => global::www.Models.PublishedModels.CompPageSettings.GetOpenGraphTitle(this, _publishedValueFallback);

		///<summary>
		/// Open Graph Type: If blank, default is "article"
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("OpenGraphType")]
		public virtual string OpenGraphType => global::www.Models.PublishedModels.CompPageSettings.GetOpenGraphType(this, _publishedValueFallback);

		///<summary>
		/// Page-Specific CSS Class: A CSS class to be appended to the body tag for this page only.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("PageCssClass")]
		public virtual string PageCssClass => global::www.Models.PublishedModels.CompPageSettings.GetPageCssClass(this, _publishedValueFallback);

		///<summary>
		/// Exclude Page from Sitemap?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "13.5.1+2e068bb")]
		[ImplementPropertyType("umbracoSitemapHide")]
		public virtual bool UmbracoSitemapHide => global::www.Models.PublishedModels.CompPageSettings.GetUmbracoSitemapHide(this, _publishedValueFallback);
	}
}
